### ISSUE TITLE
2018-01-17

### ISSUE THREAD

**Issue by ZhenhuiZhang** [YanchongCarolynChen/Applied-Statistics-Analysis-with-R#4]
早晨!:sunny:

**Comment by YanchongCarolynChen** [comment]
早啊，我现在没有完整的学习资料的哦 要上课才有

**Comment by ZhenhuiZhang** [comment]
嗯嗯好

**Comment by YanchongCarolynChen** [comment]
![image](https://user-images.githubusercontent.com/27554916/35020978-9707cbe2-fb69-11e7-9ba5-f50469eaafb8.png)

**Comment by YanchongCarolynChen** [comment]
这个怎么理解阿？我昨晚想问你问题的，可是下课回去都11点8了，洗完澡都12点多

**Comment by ZhenhuiZhang** [comment]
我看一下，
嗯嗯你有空先啦，你也累呢

**Comment by YanchongCarolynChen** [comment]
时间不够用。。。昨晚的课的作业都没时间做，我总是做错事，怎么办。。

**Comment by YanchongCarolynChen** [comment]
那个截图是来自package(stringr)里面的invert_match函数

**Comment by ZhenhuiZhang** [comment]
是工作上做的不够好吗？

**Comment by ZhenhuiZhang** [comment]
![image](https://user-images.githubusercontent.com/16443836/35021434-d49df51a-fb6b-11e7-915f-e7de9e2bbad8.png)

**Comment by ZhenhuiZhang** [comment]
这样能理解吗？

**Comment by ZhenhuiZhang** [comment]
昨晚的课的作业内容是什么呀？

**Comment by ZhenhuiZhang** [comment]
昨晚的课的作业内容是什么呀？有空跟我说一说呗

**Comment by ZhenhuiZhang** [comment]
平时工作上有什么问题可以跟我聊一聊呀，不过我也是刚刚进入职场的菜鸟啦
- 你刚刚才做相关的工作啦，之前也没什么经验
- 犯错不要紧的呢，吸取教训就好了，你老大看见你慢慢变好也会很开心的
- 每过一段时间你可以总结一下最近的工作，自省一下
- 等你工作顺手之后，就可以主动一点去跟别人学习一下基本工作之外的知识
:relaxed:

**Comment by ZhenhuiZhang** [comment]
你这个学期决定修多少门课了？

**Comment by YanchongCarolynChen** [comment]
后面的[[1]]不理解

**Comment by YanchongCarolynChen** [comment]
昨晚的课和编程无关呢。。。我能做好的，你放心啦，我不会跟你客气的

**Comment by YanchongCarolynChen** [comment]
现在是3门 我觉得我能搞定这三门就很好了

**Comment by ZhenhuiZhang** [comment]
![image](https://user-images.githubusercontent.com/16443836/35023085-1d341194-fb74-11e7-9872-c60353b7d93e.png)

**Comment by ZhenhuiZhang** [comment]
因为str_locate_all函数的结果是这样子的结构的
所以要用[[1]]去获取到那个结果的矩阵

**Comment by YanchongCarolynChen** [comment]
现在在犯错真的很害怕，特别是还有另外一个实习生和我作对比。。。我这都第二周了，还学不会聪明一点，并且我老板好像不是很喜欢我。。可能是觉得我太蠢了吧

**Comment by ZhenhuiZhang** [comment]
刚刚发的的[[1]]的说明，可以理解吗？

**Comment by ZhenhuiZhang** [comment]
你现在缺少实战经验了呢，多跟老大沟通啦，谈谈心，相信他/她也很愿意帮助你的。不能自己觉得别人不喜欢你哦。

**Comment by YanchongCarolynChen** [comment]
是因为那个函数的输出结果是一个数组么？
我好像对整个项目还不是很了解。。。sad大概知道怎么提高啦
我觉得我boss不喜欢我是有原因的，大概是因为我和他不是同一类人吧。。。

**Comment by ZhenhuiZhang** [comment]
嗯嗯对的，函数输出的结果是这样的结构
![image](https://user-images.githubusercontent.com/16443836/35024556-24355da2-fb7b-11e7-8bc3-f9031fdf7639.png)
invert_match的函数知道用法了么？

**Comment by ZhenhuiZhang** [comment]
干巴爹

**Comment by YanchongCarolynChen** [comment]
知道！

**Comment by YanchongCarolynChen** [comment]
我去。。。他们现在就说要找下一个intern是不是对我不满意阿

**Comment by ZhenhuiZhang** [comment]
他们跟你说要找吗？

**Comment by YanchongCarolynChen** [comment]
你觉得看一个数据库最重要是要看什么吖

**Comment by ZhenhuiZhang** [comment]
了解表的结构咯

**Comment by ZhenhuiZhang** [comment]
- 字段名，字段类型
- 有联系的表 之间的关系
- 主键 外键 唯一键

**Comment by ZhenhuiZhang** [comment]
然后你要学会增删改查操作， 对于你现在的工作，学会写查询应该会比较重要

**Comment by YanchongCarolynChen** [comment]
是啊，他们说要找的，我intern到6月底7月初嘛。。他们三月就要，还说我有合适的人选的话可以推荐

**Comment by YanchongCarolynChen** [comment]
好的好的 我要看数据库了

**Comment by ZhenhuiZhang** [comment]
那应该不是哦我觉得，可能是实习生人手不够啦，或者是其他的intern要走之类的，要看你的部门工作计划是不是需要招人

**Comment by YanchongCarolynChen** [comment]
我不晓得。。。不过我是觉得是我做的不够好啦。。。反正我想来这边学到东西，回去找工作，国内互联网招聘有消息记得通知我一下阿哈哈哈哈

**Comment by ZhenhuiZhang** [comment]
做好自己就好啦，
嗯嗯，数据库不需要太纠结表的结构哦，了解一下就好
你可以自己试一下写查询，在写的过程中你就会慢慢了解表的结构的，因为你需要去看字段的类型，表的关联

**Comment by ZhenhuiZhang** [comment]
看看同事或者老大能不能给些小需求你去做有关数据库的操作，
有东西做着会学的比较快

**Comment by YanchongCarolynChen** [comment]
你说parent_party_key 和primary_party_id有什么不同么

**Comment by ZhenhuiZhang** [comment]
表a有一外键，指向表b，那么b就是a的parent table,外键所指的列就是parent key

**Comment by ZhenhuiZhang** [comment]
primary_party_id是当前表的主键

**Comment by YanchongCarolynChen** [comment]
哦哦 就是说parent_key指向外键而primary_key就是当前表的主键

**Comment by ZhenhuiZhang** [comment]
嗯嗯，可以这么说
但parent_key跟外键是有一点区别的，

**Comment by ZhenhuiZhang** [comment]
你今晚要去上课吗？

**Comment by YanchongCarolynChen** [comment]
parent_key和外键的区别是什么？
等下去上课

**Comment by ZhenhuiZhang** [comment]
就是a表有一外键b_id是指向b，b_id对应b表的id，那么b表的id就是parent_key

**Comment by YanchongCarolynChen** [comment]
去上课去上课

**Comment by YanchongCarolynChen** [comment]
嗯。。其实应该跟我理解得差不多

**Comment by ZhenhuiZhang** [comment]
嗯嗯:blush:
