### ISSUE TITLE
2018-01-18

### ISSUE THREAD

**Issue by ZhenhuiZhang** [YanchongCarolynChen/Applied-Statistics-Analysis-with-R#5]
早!:sun_behind_small_cloud:

**Comment by YanchongCarolynChen** [comment]
morning！

**Comment by YanchongCarolynChen** [comment]
你这段时间工作在忙什么啊？

**Comment by YanchongCarolynChen** [comment]
数据库崩了。。休息一下

**Comment by ZhenhuiZhang** [comment]
最近没忙什么呢，自己在学习一些东西，没什么方向要学什么，想看什么就研究一下咯。

**Comment by ZhenhuiZhang** [comment]
我在[Kaggle](https://www.kaggle.com/)这个网站上面看到有很多别人分析的案例哦，有r语言的也有python的

**Comment by ZhenhuiZhang** [comment]
今天是周杰伦生日哦，你会听周杰伦的歌吗？我是看见他今天出了一首新歌《等你下课》才知道的。

**Comment by YanchongCarolynChen** [comment]
哈哈哈哈 这么久以来没听过歌。。。

**Comment by YanchongCarolynChen** [comment]
kaggle是很多资源

**Comment by ZhenhuiZhang** [comment]
你今天有什么任务做了？

**Comment by YanchongCarolynChen** [comment]
一个数据库里面可能有两个属性构成一个主键么？

**Comment by YanchongCarolynChen** [comment]
继续昨天的任务，了解数据库

**Comment by YanchongCarolynChen** [comment]
为什么join的时候要用到两个键来join呢

**Comment by ZhenhuiZhang** [comment]
- 数据库里面可以由两个属性构成一个主键的
- join是指dplyr的那些join吗？

**Comment by YanchongCarolynChen** [comment]
对的，其实是不是可以只用一个属性去join的？但是在我的case里面是因为两个属性构成了一个主键来识别唯一的一条记录，所以要用两个属性去join？

**Comment by ZhenhuiZhang** [comment]
dplyr里面的join是有个by参数的，这个参数
- 默认是null值，这时候会使用两个表中相同的属性进行连接的

**Comment by ZhenhuiZhang** [comment]
不一定两个属性构成一个主键就用两个属性去join的哦
不过一般情况下，要对应两个表中同属一个事物或者类的记录，就要用能唯一区别一个事物或者类数据的属性（一般是主键或唯一键，需要看要实现的东西拉，不是绝对的说法）

**Comment by YanchongCarolynChen** [comment]
- 哦哦，大概懂

**Comment by ZhenhuiZhang** [comment]
哦哦对了，刚刚说的不太完整
join的by参数，
- 默认是null值，这时候会使用两个表中所有相同名称的属性进行连接的

**Comment by YanchongCarolynChen** [comment]
嗯呢，这个我在用的时候了解到了

**Comment by YanchongCarolynChen** [comment]
有点迷。。。现在在看的数据都分不清主键是哪个

**Comment by ZhenhuiZhang** [comment]
你现在是通过什么去看的？

**Comment by ZhenhuiZhang** [comment]
公司的项目有没有数据库的模型文档呀？
或者你看看能不能连接到数据库去看看表的结构，这样可以看到表的构成

**Comment by YanchongCarolynChen** [comment]
我是直接看数据的

- 怎么查询出来哪个是主键？

- 没有模型文档吧，我不知道怎么看表的构成哦，只有一个框框列出了所有的属性名，然后我就查询看看例子

**Comment by ZhenhuiZhang** [comment]
“只有一个框框列出了所有的属性名”，可以给我看一下吗？

**Comment by YanchongCarolynChen** [comment]
![image](https://user-images.githubusercontent.com/27554916/35079375-edf174f2-fc41-11e7-8f7f-ef243574a2e8.png)

**Comment by YanchongCarolynChen** [comment]
我不会被zhua吧。。。。哈哈哈哈

**Comment by ZhenhuiZhang** [comment]
还有其他操作吗？

**Comment by ZhenhuiZhang** [comment]
你可以吧那条删掉的

**Comment by YanchongCarolynChen** [comment]
我就是写个select * from，不知道还能写什么了

**Comment by ZhenhuiZhang** [comment]
这个应该是一个可视化数据库管理的软件，你现在能不能在那里看到该表的数据？

**Comment by YanchongCarolynChen** [comment]
这个就是表的结构了吧？我不懂哎

**Comment by ZhenhuiZhang** [comment]
你试一下这个命令
```
desc tabl_name
```

**Comment by YanchongCarolynChen** [comment]
只有名字，类型和来源没有别的了
![image](https://user-images.githubusercontent.com/27554916/35079502-f1fc7e74-fc42-11e7-9d2a-324cc5cb0847.png)

**Comment by ZhenhuiZhang** [comment]
嗯嗯，你先把截图删除啦

**Comment by YanchongCarolynChen** [comment]
怎么样？还有别的办法么？

**Comment by ZhenhuiZhang** [comment]
![image](https://user-images.githubusercontent.com/16443836/35079696-06a44afe-fc44-11e7-896d-bf05cc05cf04.png)
你点击那里看看其他地方有没有显示出来什么？

**Comment by YanchongCarolynChen** [comment]
没有。。。就是下面的列名了。。。

**Comment by ZhenhuiZhang** [comment]
截一张整个屏幕的我看看吧，我看完你就删掉
![image](https://user-images.githubusercontent.com/16443836/35079743-62b4d638-fc44-11e7-8917-80894457be1e.png)

**Comment by ZhenhuiZhang** [comment]
你问一问同事吧 因为我也不清楚你用的工具或软件啦

**Comment by ZhenhuiZhang** [comment]
不过也没关系啦，我记得周末你给我看过一些代码，其中有一个是写了很多层子查询的语句，我觉得你可以去看一下，看看那些查询的目的，可以当作一个学习的例子:smirk:。

**Comment by YanchongCarolynChen** [comment]
好的 我在看
