### ISSUE TITLE
22-Jan-2018

### ISSUE THREAD

**Issue by YanchongCarolynChen** [YanchongCarolynChen/Applied-Statistics-Analysis-with-R#7]
morning!

**Comment by ZhenhuiZhang** [comment]
早啊早啊

**Comment by ZhenhuiZhang** [comment]
今天雾霾很大啊
![image](https://user-images.githubusercontent.com/16443836/35201399-e3ddbe32-ff55-11e7-8224-380bb01b707a.png)

**Comment by ZhenhuiZhang** [comment]
你现在在做什么工作呀？

**Comment by YanchongCarolynChen** [comment]
哦，你要来新加坡看看，无霾的天气~
今天还是继续看代码。。。好尬

**Comment by ZhenhuiZhang** [comment]
嗯嗯，
上一个issue最后讨论的那个问题还要看么？

**Comment by ZhenhuiZhang** [comment]
嗯嗯，我也工作啦

**Comment by ZhenhuiZhang** [comment]
你能访问这个网站不:point_down:
[SegmentFault](https://segmentfault.com/blogs)

**Comment by YanchongCarolynChen** [comment]
能哦

**Comment by YanchongCarolynChen** [comment]
你现在又有新的project做么？

**Comment by ZhenhuiZhang** [comment]
嗯嗯:ok_hand:
现在没有了，我在看资料,
你有没有啥东西想要去做的？我有时间看一看

**Comment by YanchongCarolynChen** [comment]
我想学python
但是是不是要从syntax开始学起啊？
我现在有点乱，R和python转换不过来
正确的学习方法是啥？
你昨天给我讲的那个爬虫的解决方法其实我还没搞懂

**Comment by ZhenhuiZhang** [comment]
我看你给我的资料会特有效率啊，哈哈哈哈

**Comment by YanchongCarolynChen** [comment]
。。。。你喜欢看英文资料？

**Comment by YanchongCarolynChen** [comment]
table_names <- sapply(queries, function(x) { 
  str_extract(x, "(?<=CREATE TABLE ).*(?= AS)")
})

- 这个怎么理解？其实r里面怎么自定义函数我都不是很懂

**Comment by ZhenhuiZhang** [comment]
syntax看一看吧，记一记语法先
我昨天给你讲的爬虫和http的一些知识，
会不会理解起来有点难呀？

**Comment by ZhenhuiZhang** [comment]
等等，我整理一下再发给你

**Comment by ZhenhuiZhang** [comment]
这段代码的目的应该是提取表名

- queries应该是储存查询语句的表格
- 自定义函数里的逻辑是提取语句中在 CREATE TABLE 字符串（命令）后面 到 AS 字符串前的字符串，就是表名的位置
![image](https://user-images.githubusercontent.com/16443836/35202256-8d721334-ff5c-11e7-9527-a3be9ea8b8b6.png)

![image](https://user-images.githubusercontent.com/16443836/35202243-7baf9f2c-ff5c-11e7-970b-6e1aadd0167b.png)


```
table_names <- sapply(queries, function(x) {
    str_extract(x, "(?<=CREATE TABLE ).*(?= AS)")
})
```

**Comment by ZhenhuiZhang** [comment]
得出表里面每一条创建数据表语句的表名，应该是这样
```
table_names <- sapply(queries, function(x) {
    str_extract(x, "(?<=CREATE TABLE ).*(?= AS)")
})
```

**Comment by YanchongCarolynChen** [comment]
syntax看一看吧，记一记语法先--〉好的，那你给我找找资料？可以速成的那种？[懒鬼就是我]
我昨天给你讲的爬虫和http的一些知识，会不会理解起来有点难呀？--〉其实还好，可能是因为我太聪明了吧

**Comment by ZhenhuiZhang** [comment]
![image](https://user-images.githubusercontent.com/16443836/35202451-caa7dfa8-ff5d-11e7-8771-be4cdd3f1f33.png)

你试一下运行,看看
```
queries <- c('CREATE TABLE test_table_name AS',  'SELECT party_key FROM b_table p', 'CREATE TABLE ads AS', 'hello')

table_names <- sapply(queries, function(x) {
     str_extract(x, "(?<=CREATE TABLE ).*(?= AS)")
})

table_names 
```

**Comment by YanchongCarolynChen** [comment]
好的

**Comment by ZhenhuiZhang** [comment]
速成的没有哦， 那你还要不要？:nerd_face:，
有空再跟你说一说http的其他知识

**Comment by YanchongCarolynChen** [comment]
速成的没有哦， 那你还要不要？:nerd_face:，---〉勉强接受吧。。。包会么老师？
有空再跟你说一说http的其他知识---〉现在？今天很闲，看懂代码就好了

**Comment by ZhenhuiZhang** [comment]
现在啊，你电脑有jupyter么？

**Comment by YanchongCarolynChen** [comment]
沃草！你怎么这么厉害能看懂那个自定义函数。。。

**Comment by ZhenhuiZhang** [comment]
当然！

**Comment by ZhenhuiZhang** [comment]
你要好好补一下变量的储存的知识了，我发现你的问题了哈

**Comment by ZhenhuiZhang** [comment]
学不会你自己看看点惩罚

**Comment by YanchongCarolynChen** [comment]
哈哈哈 怎么办。。。求补课

**Comment by YanchongCarolynChen** [comment]
没办法。。。在公司，又没有wifi
我自己电脑也没带

**Comment by ZhenhuiZhang** [comment]
你电脑也看不了我分享的呢

**Comment by ZhenhuiZhang** [comment]
你先看公司项目的代码吧:blush:
了解了解项目的架构

**Comment by YanchongCarolynChen** [comment]
okay

**Comment by YanchongCarolynChen** [comment]
终于有任务来了。。。呜呜呜等得好苦

**Comment by ZhenhuiZhang** [comment]
:yum:
